### ISSUE TITLE
Unable to create CRDs for rook ceph

### ISSUE THREAD

**Issue by MichaelKora** [MathiasPius/kronform#2]
hey @MathiasPius..am new to TalOS ... while seting up up a rook-ceph cluster, i started deplyoying the operator and run in the follwoing error 

> error: resource mapping not found for name: "rook-ceph" namespace: "rook-ceph" from "rook-ceph-operator.yaml": no matches for kind "HelmRelease" in version "helm.toolkit.fluxcd.io/v2beta1"

any idea what i should do? i expected the rook-ceph file to install the crds

**Comment by MathiasPius** [comment]
The `HelmRelease.helm.toolkit.fluxcd.io/v2beta1` custom resource definition is deployed by FluxCD, but it looks like a `v2beta2` has been released, I just haven't updated Flux yet :)

Try changing all HelmRelease references from `v2beta1` to `v2beta2`

**Comment by MichaelKora** [comment]
thanks that works for me..but deploying the rook-ceph.yaml and cluster.yaml dont create any resource in the cluster

**Comment by MathiasPius** [comment]
It might take a little while for Flux to pick up the HelmRelease resources and deploy them.

Flux might also be experiencing some issues, you can check the status of it using [flux get helmreleases](https://fluxcd.io/flux/cmd/flux_get_helmreleases/)

**Comment by MichaelKora** [comment]
✗ no HelmRelease objects found in "flux-system" namespace..

i'll wait some time then

**Comment by MichaelKora** [comment]
i dont knwo if a `flux bootstrap gitlab \
  --deploy-token-auth \
  --owner=my-gitlab-username \
  --repository=my-project \
  --branch=master \
  --path=clusters/my-cluster \
  --personal` is necessary

**Comment by MathiasPius** [comment]
The HelmRelease should have been deployed in the `rook-ceph` namespace, can you try `flux get helmreleases -n rook-ceph`?

**Comment by MichaelKora** [comment]
> NAME            REVISION        SUSPENDED       READY   MESSAGE
> rook-ceph                       False           False   waiting to be reconciled

**Comment by MathiasPius** [comment]
Looks like Flux might not have been installed, or isn't running in your cluster.

Is there a pod running in the `flux-system` cluster, and if so, does the log for it indicate any kind of issue?

**Comment by MichaelKora** [comment]
no ..i dont have a `flux-system` ns

**Comment by MichaelKora** [comment]
`flux install` returned 
`✗ install failed: Namespace/flux-system dry-run failed (InternalError): Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces.create-non-kubesystem": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": context deadline exceeded`

**Comment by MathiasPius** [comment]
This looks like a rancher-specific issue, which I unfortunately don't have much experience with. It seems like this [Rancher Webhook](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook) might be the source of the issue. Perhaps the underlying service is not working correctly?

**Comment by MichaelKora** [comment]
i was able to fix that issue...however deploying `rook-ceph` shows the followinf status
`failed to cache index to temporary file: G ││ et "https://charts.rook.io/release/index.yaml": dial tcp xx.xx.xx.xx.:443: i/o timeout `

**Comment by MichaelKora** [comment]
P.S i used just `flux install` without any bootstrap before starting install `rook-ceph.yaml`

**Comment by MichaelKora** [comment]
i fixed the issue and came far enough to create the pvc...but it is in pending state and cant create the PV:

```
Normal  Provisioning          92s                rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-546f986db6-knlch_863ef4f8-d8bc-4b22-b6ed-426b0858d38e  External provisioner is provisioning volume for claim "default/test-pvc"
 Normal  ExternalProvisioning  10s (x7 over 92s)  persistentvolume-controller waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
```

did i oversee something ?

**Comment by MichaelKora** [comment]
@MathiasPius  i finally create the PV manually and bound it to the PVC...it worked that way but it is not optimal

**Comment by MathiasPius** [comment]
Is it possible the pool was not configured correctly? It should be possible to see why the operator is not provisioning the PV from the container logs.

**Comment by MichaelKora** [comment]
@MathiasPius  

> csi-snapshotter E0408 09:14:29.754580       1 reflector.go:147] github.com/kubernetes-csi/external-snapshotter/client/v7/informers/externalversions/factory.go:142: Failed to watch *v1.VolumeSnapshotContent: failed to list *v1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
